Test Kitchen Config Refactor
osuosl-cookbooks/osl-gpu pull request #4
Opened 2024-05-08 22:22 UTC by zwall-bp

Errors present in Vagrant and Dokken

2024-07-24 21:20 UTC, ramereth requested changes

2024-07-24 21:20 UTC, ramereth commented on kitchen.dokken.yml
> +  chef_version: <%= ENV['CHEF_VERSION'] || '17' %>
```suggestion
  chef_version: <%= ENV['CHEF_VERSION'] || '18' %>
```

2024-07-24 21:20 UTC, ramereth commented on kitchen.yml
> +  product_version: '17'
```suggestion
  product_version: '18'
```

2024-07-24 21:55 UTC, ramereth commented
@zwall-bp please make sure you rebase this

2024-10-21 21:54 UTC, zwall-bp commented
Only issues present are in the `*-runfile-*` resources, in verification, as there are issues parsing for the kernel version.

Ignored dokken tests, as installing drivers goes too low level for Docker's abilities.

2024-10-22 20:10 UTC, ramereth commented
@zwall-bp I recommend you just remove the dokken kitchen completely. There's very little this cookbook would benefit from dokken.

2024-10-22 22:19 UTC, ramereth commented on kitchen.yml
> +  product_version: '17'
This still needs to be addressed.

2024-10-22 22:26 UTC, ramereth commented
@zwall-bp also please add Ubuntu 20.04 to `kitchen.yml`

2024-10-23 16:29 UTC, ramereth commented on kitchen.openstack.yml
> +      image_ref: "almalinux 8"
```suggestion
      image_ref: "AlmaLinux 8"
```

2024-10-25 16:51 UTC, merged